export const initialMenuPanels = [
  {
    key: 'starters',
    title: 'Starters',
    sortOrder: 1,
    bannerNote: 'Perfect for sharing at the table',
    items: [
      { name: 'Cheese Curds', note: 'Cheese Curds Fried with Ranch Sauce', price: '$10' },
      { name: 'Parmesan French Fries', note: 'Garlic parmesan coated french fries', price: '$10' },
      { name: 'Crispy Pork Belly Bites', note: 'Served with BBQ Sauce and Sesame Seeds', price: '$9' },
      { name: 'Bone-In Wings', note: 'Fried with BBQ, Parmesan Garlic, hot honey or hot Sauce', price: '$13' },
    ],
  },
  {
    key: 'sandwiches',
    title: 'Sandwiches',
    sortOrder: 2,
    bannerNote: 'Served alongside your choice of French fries (plain or Parmesan), sweet potato fries, or chips',
    items: [
      { name: 'Classic Club Sandwich', note: 'Ham, Turkey, bacon, lettuce, tomato, Cheddar and swiss on toasted white bread With Mayo', price: '$15' },
      { name: 'Cheeseburger', note: 'Cheddar, Bacon, lettuce, onion, tomato, pickle', price: '$16' },
      { name: 'Patty Melt', note: 'Grilled onions, Pub Sauce, swiss, American cheese, rye bread', price: '$16' },
      { name: 'Grilled Chicken Sandwich', note: 'A toasted bun with chicken, lettuce, tomato, onion', price: '$16' },
    ],
  },
  {
    key: 'salads',
    title: 'Dinner Salads',
    sortOrder: 3,
    bannerNote: 'Dressings: Homemade Ranch, Italian, French, Blue Cheese, Honey Mustard, Balsamic Vinaigrette, 1000 Island',
    items: [
      { name: 'Chicken Caesar Salad', note: 'Parmesan, croutons, caesar dressing · Chicken fried or Grilled', price: '$15' },
      { name: 'House Salad', note: 'Lettuce, tomatoes, red onion, cheese, croutons, choice of dressing', price: '$15' },
      { name: 'Chef Salad', note: 'Ham, Bacon, Cheese, Eggs, Tomatoes, Sweet peppers, Croutons, choice of dressing', price: '$15' },
    ],
  },
  {
    key: 'pastas',
    title: 'Pastas',
    sortOrder: 4,
    bannerNote: 'Served with a choice of a side house salad or a side Caesar salad, and garlic bread',
    items: [
      { name: 'Spaghetti', note: 'Marinara or meat sauce', price: '$15' },
      { name: 'Fettuccine Alfredo', note: 'Creamy Alfredo Sauce with Grilled Chicken and Noodles', price: '$16' },
      { name: 'Mushroom Ravioli Portabella', note: 'Mushroom stuffed ravioli with Alfredo sauce', price: '$18' },
    ],
  },
  {
    key: 'entrees',
    title: 'Entrees',
    sortOrder: 5,
    bannerNote: 'Served with House or Caesar salad, plus one extra side of your choice',
    items: [
      { name: 'Blackened Salmon', note: 'Grilled Blackened Salmon', price: '$23' },
      { name: 'Chicken Tenders', note: 'Crispy, breaded, and fried chicken tenders served with your choice of dipping sauce: Parmesan garlic, Honey spicy, hot, ranch, honey mustard, or pub sauce', price: '$16' },
      { name: 'Grilled Chicken Breast', note: 'Grilled Chicken Breast with Seasoning', price: '$18' },
    ],
  },
  {
    key: 'pizza',
    title: '16" Thin Crust Pizza',
    sortOrder: 6,
    bannerNote: 'Specials 16 Inch Pizza Thin Crust | Toppings Available ($1.95 each): Beef, Black Olives, Canadian Bacon, Cheese, Extra Cheese, Extra Sauce, Garlic, Green Olives, Green Peppers, Pineapple, Mushrooms, Onions, Pepperoni, Red Onion, Sausage, Tomato',
    items: [
      { name: 'Deluxe Pizza', note: 'Pepperoni, Sausage, Onions, Green Peppers, Mushrooms, Green Olives', price: '$25' },
      { name: 'Meat Lovers Pizza', note: 'Pepperoni, Sausage, Beef, Canadian Bacon', price: '$25' },
      { name: 'Single Topping 16" Pizza', note: 'Build your own thin crust pizza · Each additional topping $1.95', price: '$20' },
    ],
  },
  {
    key: 'kids-meals',
    title: 'Kids Meals',
    sortOrder: 7,
    bannerNote: 'Includes choice of fountain drink',
    items: [
      { name: 'Kids Spaghetti', note: 'Marinara or Meat Sauce, Served with garlic bread', price: '$9' },
      { name: 'Kids Chicken Strips', note: 'Served with fries or chips', price: '$9' },
      { name: 'Kids Quesadilla', note: 'Served with Fries or Chips', price: '$9' },
    ],
  },
  {
    key: 'sides',
    title: 'Sides',
    sortOrder: 8,
    bannerNote: 'Available as sides with your meal or ala carte',
    items: [
      { name: 'French Fries', note: 'Plain or Parmesan coated crispy french fries' },
      { name: 'Sweet Potato Fries', note: 'Crispy sweet potato fries' },
      { name: 'Baked Potato', note: 'Classic baked potato' },
      { name: 'Stir Fry', note: 'Seasoned stir-fry vegetables' },
      { name: 'Side House Salad', note: 'Fresh greens with choice of dressing' },
      { name: 'Side Caesar Salad', note: 'Crispy romaine, parmesan, croutons & Caesar dressing' },
      { name: 'Chips', note: 'Crispy potato chips' },
    ],
  },
  {
    key: 'drinks',
    title: 'Drinks',
    sortOrder: 9,
    bannerNote: 'Refreshing fountain sodas & house-brewed teas',
    items: [
      { name: 'Fountain Soda', note: 'Pepsi, Pepsi Zero, Dr Pepper, Dr Pepper Zero, Mountain Dew, Mountain Dew Code Red, Lemonade, Root Beer, Orange Crush, 7 Up' },
      { name: 'Sweet or Unsweet Tea', note: 'House-brewed sweet or unsweet tea' },
    ],
  },
  {
    key: 'cocktails',
    title: 'Signature Cocktails',
    sortOrder: 10,
    bannerNote: 'From a classic Old Fashioned to custom twists — our bartenders craft your favorite drink',
    items: [
      { name: 'New Beginnings', note: 'Bright passionfruit, crisp tequila, and a sparkling toast to what’s next' },
      { name: 'Crème Brûlée Whiskey Sour', note: 'Silky whiskey sour finished with a crisp, caramelized sugar crust · Rich & creamy' },
      { name: 'Hot Honey Old Fashioned', note: 'Featuring Southern Illinois’ Sons of Mitches Whiskey, house hot honey syrup & bitters · Sweet, hot, or extra hot' },
      { name: 'Peach Tea Mule', note: 'Vodka, peach liqueur, house-brewed sweet tea & ginger beer · Southern Illinois staple' },
    ],
  },
]

export const initialLineupShows = [
  { dateStr: '2026-07-22', day: 'Jul 22', weekday: 3, act: 'Christopher John Davis Chamness', genre: 'Acoustic & Vocals', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'JUL', facebookUrl: 'https://facebook.com/events', socialUrl: '' },
  { dateStr: '2026-07-29', day: 'Jul 29', weekday: 3, act: 'Taylor Kearney', genre: 'Live Performance', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'JUL', facebookUrl: 'https://facebook.com/events', socialUrl: '' },
  { dateStr: '2026-08-05', day: 'Aug 5', weekday: 3, act: 'Jermaine Bollinger', genre: 'Live Music', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'AUG', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-08-12', day: 'Aug 12', weekday: 3, act: 'Tim Crosby', genre: 'Singer-Songwriter', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'AUG', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-08-26', day: 'Aug 26', weekday: 3, act: 'Max Dalton', genre: 'Live Performance', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'AUG', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-09-09', day: 'Sep 9', weekday: 3, act: 'Saint City 2', genre: 'Live Performance', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'SEP', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-09-16', day: 'Sep 16', weekday: 3, act: 'Isaiah Cunningham', genre: 'Acoustic Set', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'SEP', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-09-23', day: 'Sep 23', weekday: 3, act: 'Edwin Linson', genre: 'Live Performance', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'SEP', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-09-30', day: 'Sep 30', weekday: 3, act: 'Jonny Coller', genre: 'Live Music', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'SEP', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-10-07', day: 'Oct 7', weekday: 3, act: 'Max Dalton', genre: 'Live Performance', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'OCT', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-10-14', day: 'Oct 14', weekday: 3, act: 'Christopher John Davis Chamness', genre: 'Acoustic & Vocals', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'OCT', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-10-21', day: 'Oct 21', weekday: 3, act: 'Matt Basler', genre: 'Live Music', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'OCT', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-10-28', day: 'Oct 28', weekday: 3, act: 'Logan Allen Chapman', genre: 'Live Performance', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'OCT', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-11-04', day: 'Nov 4', weekday: 3, act: 'Isaiah Cunningham', genre: 'Live Music', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'NOV', facebookUrl: '', socialUrl: '' },
  { dateStr: '2026-12-02', day: 'Dec 2', weekday: 3, act: 'Jermaine Bollinger', genre: 'Live Music', category: 'Live Music', hour: 17.5, endHour: 20.5, monthKey: 'DEC', facebookUrl: '', socialUrl: '' },
]
